# Protocolos
STOP_AND_WAIT="stop_and_wait"
SELECTIVE_REPEAT="selective_repeat"
STOP_AND_WAIT_PROTOCOL=0
SELECTIVE_REPEAT_PROTOCOL=1

# Tipos de paquetes (como constantes)
TYPE_SYN = 0
TYPE_SYN_ACK = 1
TYPE_ACK = 2
TYPE_DATA = 3
TYPE_CLOSE = 4
TYPE_NACK = 5
TYPE_CLOSE_ACK = 6

HEADER_FORMAT = "!III" # ! = ordenado Big Endian ; I = 4 bytes integer => 12 bytes header
PAYLOAD_SIZE = 1400 # bytes
HEADER_SIZE = 12 # bytes
WINDOW_SIZE = 20

# MTU Estándar (1500) / PAYLOAD_SIZE (1400) + HEADER_SIZE (12) + Header IP (20) + Header UDP (8) + Header Ethernet (14) + Margen de seguridad = 2048
BUFFER_SIZE = 2048

OP_TYPE_UPLOAD = 1
OP_TYPE_DOWNLOAD = 0

INFO_FIELD_SIZE = 32
PKT_TYPE_FIELD_SIZE = 3
OP_TYPE_FIELD_SIZE = 1
PROTOCOL_FIELD_SIZE = 1
PAYLOAD_LENGTH_FIELD_SIZE = 27
CRC_FIELD_SIZE = 32
ID_FIELD_SIZE = 32



PKT_TYPE_MASK = 0x7 # not used
PAYLOAD_LENGTH_MASK = 0x7FFFFFF
PROTOCOL_MASK = 0x1
OP_TYPE_MASK = 0x1

# 100 GB en bytes (100 * 1024 * 1024 * 1024)
MAX_FILE_SIZE = 107374182400

ACK_TIMEOUT = 0.5
MAX_RETRIES = 10

# EVENTS

EVENT_TYPE_SYN = 1
EVENT_TYPE_HANDSHAKE = 2
EVENT_TYPE_ACK = 3
EVENT_TYPE_DATA = 4
EVENT_TYPE_SYN_ACK = 5
EVENT_TYPE_CLOSE = 6
EVENT_TYPE_ACK_INIT = 7
EVENT_TYPE_CLOSE_FIN = 8